package com.quran.labs.androidquran.common.audio

import com.quran.data.model.audio.Qari

val defaultQaris: List<Qari> = listOf(
  Qari(
    0,
    R.string.qari_minshawi_murattal_gapless,
    "https://download.quranicaudio.com/quran/muhammad_siddeeq_al-minshaawee/",
    "minshawi_murattal",
    false,
    "minshawi_murattal"
  ),
  Qari(
    1,
    R.string.qari_husary_gapless,
    "https://download.quranicaudio.com/quran/mahmood_khaleel_al-husaree/",
    "husary",
    false,
    "husary"
  ),
  Qari(
    2,
    R.string.qari_basfar,
    "https://download.quranicaudio.com/quran/abdullaah_basfar/archive/",
    "abdullah_basfar",
    false,
    "abdullah_basfar"
  ),
  Qari(
    3,
    R.string.qari_sudais_gapless,
    "https://download.quranicaudio.com/quran/abdurrahmaan_as-sudays/",
    "sudais_murattal",
    false,
    "sudais_murattal"
  ),
  Qari(
    4,
    R.string.qari_shuraym_gapless,
    "https://download.quranicaudio.com/quran/sa3ood_al-shuraym/",
    "shuraym",
    false,
    "shuraym"
  ),
  Qari(
    5,
    R.string.qari_muaiqly_haramain_gapless,
    "https://mirrors.quranicaudio.com/tvquran/maher_al_mu3aiqly/",
    "maher_al_muaiqly",
    false,
    "maher_al_muaiqly"
  ),
  Qari(
    6,
    R.string.qari_saad_al_ghamidi_gapless,
    "https://download.quranicaudio.com/quran/sa3d_al-ghaamidi/complete/128kbps/",
    "sa3d_alghamidi",
    false,
    "sa3d_alghamidi"
  ),
  Qari(
    7,
    R.string.qari_yasser_dussary_gapless,
    "https://download.quranicaudio.com/quran/yasser_ad-dussary/",
    "yasser_dussary",
    false,
    "yasser_dussary"
  ),
  Qari(
    8,
    R.string.qari_afasy_gapless,
    "https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/",
    "mishari_alafasy",
    false,
    "mishari_alafasy"
  ),
  Qari(
    9,
    R.string.qari_abdulaziz_zahrani_gapless,
    "https://download.quranicaudio.com/quran/abdulaziz_bin_saleh_alzahrani/",
    "abdulaziz_zahrani",
    false,
    "abdulaziz_zahrani"
  ),
  Qari(
    10,
    R.string.qari_qatami_gapless,
    "https://download.quranicaudio.com/quran/nasser_bin_ali_alqatami/",
    "qatami",
    false,
    "qatami"
  ),
  Qari(
    11,
    R.string.qari_idrees_abkar_gapless,
    "https://download.quranicaudio.com/quran/idrees_abkar/",
    "idrees_abkar",
    false,
    "idrees_abkar"
  )
)
